apiVersion: apps/v1
kind: Deployment
metadata:
  name: chisel-operator
  namespace: chisel-operator-system
  labels:
    app: chisel-operator
spec:
  selector:
    matchLabels:
      app: chisel-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: chisel-operator
    spec:
      serviceAccountName: chisel-operator
      automountServiceAccountToken: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: chisel-operator
          image: pbstriker38/chisel-operator:v0.2.1
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
          env:
            - name: RUST_LOG
              value: "debug"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
